# CONTACTOS

SEQUERAWJ="http://sites.google.com/view/wjsequera"
MOUREDEV_TWICH="https://twitch.tv/mouredev"
# SPONSORS
ELGATO_URL=""
MVP_URL=""

#SENSOR HOME SERVER
EXTERNAL_IP="200.44.212.244"
EXTERNAL_PORT=1002
LOCAL_IP ="192.168.0.104"
LOCAL_PORT=80
# AL LA CLASE SOCK
IP=EXTERNAL_IP
PORT=EXTERNAL_PORT